name: food_save
description: "Application FoodSave - Gestion intelligente des aliments selon les standards NYTH"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.8
  go_router: ^14.2.7
  
  # State Management
  provider: ^6.1.2
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  
  # HTTP & API
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  
  # Local Storage
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Backend & Database
  supabase_flutter: ^2.5.6
  
  # Security
  crypto: ^3.0.3
  flutter_secure_storage: ^9.2.2
  
  # Environment Configuration
  flutter_dotenv: ^5.1.0
  
  # Image & File Handling
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  path_provider: ^2.1.2
  
  # Location Services
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  
  # Notifications natives
  flutter_local_notifications: ^16.3.0
  awesome_notifications: ^0.9.1
  
  # Utilities
  intl: ^0.19.0
  logger: ^2.4.0
  equatable: ^2.0.5
  uuid: ^4.4.0
  permission_handler: ^11.1.0
  
  # Code Generation
  freezed_annotation: ^2.4.4
  
  # Testing & Validation
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # Code Generation
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  freezed: ^2.5.7
  
  # Testing
  mockito: ^5.4.4
  bloc_test: ^9.1.7

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Configuration and environment files
  assets:
    - .env
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
